version: "2"
services:
    web:
        build: .
        ports: 
            - "8013:80"
        volumes:
            - ./web:/var/web/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: users
            MYSQL_USER: mastari
            MYSQL_PASSWORD: mastari
            MYSQL_ROOT_PASSWORD: mastari
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
        phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: mastari
            MYSQL_PASSWORD: mastari
            MYSQL_ROOT_PASSWORD: mastari
volumes:
    persistent: